---
- name: Nettoyer le serveur de Test par defaut, sinon cible=all pour tout
  hosts: "{{ cible | default('test') }}"
  become: true

  tasks:
    - name: Supprimer le conteneur postgres s'il existe
      community.docker.docker_container:
        name: db_postgres
        state: absent

    # - name: Supprimer le dossier de donnees (Attention ca supprime toutes les donnees)
    #   ansible.builtin.file:
    #     path: /opt/postgres_data
    #     state: absent
