---
# ETAPE 1 : On demande a Ansible de recuperer les infos de dev
- name: Collecte des infos de Dev
  hosts: server-dev
  gather_facts: true

# ETAPE 2 : On fait le test depuis le serveur de test
- name: Test de connectivite BDD interne
  hosts: server-test
  gather_facts: true
  tasks:
    - name: Tentative de connexion sur l'IP PRIVEE de Dev
      ansible.builtin.wait_for:
        # Maintenant que l'etape 1 est faite, cette variable existe !
        host: "{{ hostvars['server-dev']['ansible_default_ipv4']['address'] }}"
        port: 5432
        state: started
        timeout: 10
      register: connect_result

    - name: Afficher le succes
      ansible.builtin.debug:
        msg: "Succes ! Connexion etablie via le reseau prive AWS ({{ hostvars['server-dev']['ansible_default_ipv4']['address'] }})."
